Support encoding/decoding of parameterized records
mongodb/mongo-java-driver pull request #1005
Opened 2022-09-28 19:23 UTC by jyemin

JAVA-4740

2022-09-28 19:28 UTC, jyemin commented on bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java
> +        if (clazz.getTypeParameters().length > 0) {
In this state, the codec is unusable unless it is first parameterized.  That effectively means that we don't support encoding records where the outermost record has type parameters.  This is the same restriction as we have for POJOs.

2022-09-28 19:28 UTC, jyemin commented on bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java
> +        private static int getIndexOfTypeParameter(final String typeParameterName, final Class<?> recordClass) {
This looks a bit strange, but the reflection API requires that you match up type parameters by their index in the respective arrays.

2022-09-28 19:33 UTC, jyemin commented
Initially I didn't consider the case where the type parameter was used directly as the type of one of the record components.  I wonder if I'm missing anything else.  Please try to think of other test cases.

2022-09-29 20:56 UTC, jyemin commented
Unfortunately, this doesn't handle the case of a parameterized record with cyclical type references.  If you attempt to create codecs for this set of records:

```
record TestSelfReferentialHolderRecord(
                                             @BsonId String id,
                                              TestSelfReferentialRecord<String> selfReferentialRecord) {}


public record TestSelfReferentialRecord<T>(
                                        T name,
                                        @Nullable TestSelfReferentialRecord<T> left,
                                        @Nullable TestSelfReferentialRecord<T> right) {}
```

you'll get an infinite recursion resulting in a StackOverflowException:

```
	at org.bson.codecs.record.RecordCodec.<init>
	at org.bson.codecs.record.RecordCodec.parameterize
	at org.bson.codecs.record.RecordCodec$ComponentModel.computeCodec
	at org.bson.codecs.record.RecordCodec$ComponentModel.<init>
	at org.bson.codecs.record.RecordCodec.getComponentModels
	at org.bson.codecs.record.RecordCodec.<init>
```
and so on.  There is nothing to break the cycle.  

To fix this we need to break the cycle.  But I think that can be the subject of another ticket and PR.  This one adds value even if it doesn't handle cycles.

2022-09-30 11:43 UTC, rozza requested changes
Add a regression test case for the resolving of types which move.

Add a ticket for the self referential example

2022-09-30 13:16 UTC, jyemin commented on bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java
> +        private static int getIndexOfTypeParameter(final String typeParameterName, final Class<?> recordClass) {
Thanks, I like this test.  

Done

2022-09-30 13:19 UTC, rozza approved these changes
One nit - location of the records.

Other than that LGTM

2022-09-30 13:21 UTC, jyemin commented on bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java
> +    record TestRecordWithNestedParameterizedRecord(
Oh, I was going to ask you about that, and then I forgot.  It seems better, now that I realize it's possible, to just embed the records in line like this.  If you agree, I would just move them all in a separate commit.  But either way, I can move these to where the rest of them are, to be consistent.

2022-09-30 13:23 UTC, rozza commented on bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java
> +    record TestRecordWithNestedParameterizedRecord(
Happy either way - its nice and accessible that they are inline with the tests so I'm leaning towards this change.

2022-09-30 13:24 UTC, rozza approved these changes
LGTM

2022-09-30 13:25 UTC, jyemin commented on bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java
> +    record TestRecordWithNestedParameterizedRecord(
ok, i will follow up with that later.

2022-09-30 14:57 UTC, katcharov approved these changes
LGTM

2022-09-30 15:06 UTC, merged