Bson-kotlinx
mongodb/mongo-java-driver pull request #1099
Opened 2023-03-22 12:28 UTC by rozza

Library adds the initial Kotlinx serialization support via the codec registry. Not intended to be used outside the code registry. Bson annotations are not supported by the kotlinx serialization framework. Kotlinx annotations should be used instead, where appropriate.

Supports Kotlin data types, ObjectId and BsonValues. Alternative types should provide their own serializers. See the kotlinx serialization documentation for more information.

JAVA-4873

2023-03-23 22:03 UTC, zigzago requested changes

2023-03-23 22:03 UTC, zigzago commented on bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonDecoder.kt
> +                    val indexOfNullableElement = elementsIsNullableIndexes!!.indexOfFirst { it }
It's better to write:
val isNullableIndexes = elementsIsNullableIndexes ?: error("elementsIsNullableIndexes may not be null)
val indexOfNullableElement = isNullableIndexes.indexOfFirst { it }

And also remove !! of line 98

2023-03-28 12:58 UTC, rozza commented on bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonDecoder.kt
> +            when (reader.state!!) {
Done

2023-03-30 13:23 UTC, jyemin commented
Removed myself from reviewers

2023-03-30 13:31 UTC, closed without merging