Replace `@Evolving` with `@Sealed` where appropriate
mongodb/mongo-java-driver pull request #1141
Opened 2023-06-09 01:35 UTC by stIncMale

I changed only program elements annotated with `@Beta` because changing others is not a backward-compatible change.

2023-06-09 01:35 UTC, stIncMale commented on driver-core/src/main/com/mongodb/annotations/Sealed.java
> + * it must not be extended or implemented by users.
Note the documentation change.

2023-06-09 01:36 UTC, stIncMale commented on driver-core/src/main/com/mongodb/annotations/Evolving.java
> + * @see Sealed
Note the documentation change.

2023-06-09 01:41 UTC, stIncMale commented on driver-core/src/main/com/mongodb/annotations/Evolving.java
`Evolving` should have been annotated with `@Sealed` rather than `@Evolving`, but the idea of `@Sealed` did not come at that time, and now it will be a breaking change, even though one may be quite sure that no one extended `Evolving`.

2023-06-09 12:46 UTC, jyemin commented
@stIncMale I think a change like this deserves a JAVA ticket first.

2023-06-09 13:46 UTC, stIncMale commented
@jyemin Done. Added the link to the PR description.

2023-06-12 21:20 UTC, jyemin requested changes

2023-06-12 21:20 UTC, jyemin commented on driver-core/src/main/com/mongodb/annotations/Sealed.java
> + * it must not be extended or implemented by users.
users -> consumers of the library

"users" is kind of a fuzzy work
?

2023-06-12 21:20 UTC, jyemin commented on driver-core/src/main/com/mongodb/annotations/Evolving.java
> + *     <td>Doing so facilitates writing user unit tests by creating a fake implementation.</td>
user => application

perhaps?

2023-06-12 21:43 UTC, jyemin approved these changes

2023-06-15 15:27 UTC, katcharov approved these changes
LGTM

2023-06-15 15:29 UTC, stIncMale commented on driver-core/src/main/com/mongodb/annotations/Evolving.java
> + * @see Sealed
It's because both apply there.

2023-06-16 16:53 UTC, merged