Deprecate Stream-related API
mongodb/mongo-java-driver pull request #1195
Opened 2023-09-11 22:51 UTC by jyemin

Adds:

* TransportSettings abstract class
* NettyTransportSettings subclass of TransportSettings
* A new method on MongoClientSettings to configure TransportSettings

Deprecates:

* MongoClientSettings#streamFactoryFactory
* NettyStreamFactoryFactory
* NettyStreamFactory
* AsynchronousSocketChannelStreamFactory
* AsynchronousSocketChannelStreamFactoryFactory
* BufferProvider
* SocketStreamFactory
* Stream
* StreamFactory
* StreamFactoryFactory
* TlsChannelStreamFactoryFactory

JAVA-5051

2023-09-11 23:13 UTC, jyemin reviewed
Couple of things:

Though JEP 211 indicates that it should be otherwise, and my testing directly with javac confirms the expected behavior, when building the driver I'm getting warnings about imports of classes/interfaces that have been deprecated.  I'm not sure why, or what to do about it.  Options:

1. Fully qualify all references to deprecated types so that the imports can be removed
2. Disable linting for deprecation
3. Live with the warnings until it's time to remove the deprecated types for 5.0

Scala test `The_scala_package_should_mirror_parts_of_com.mongodb.connection_in_org.mongdb.scala.connection` is passing by adding exceptions for the two new classes.  Not sure whether to add Scala wrappers for them instead.

2023-09-12 21:50 UTC, stIncMale requested changes

2023-09-12 22:09 UTC, jyemin commented on driver-core/src/main/com/mongodb/annotations/Evolving.java
> - *     <td>Doing so allows customizing API behavior.</td>
Agreed

2023-09-12 22:10 UTC, jyemin commented on driver-core/src/main/com/mongodb/connection/NettyTransportSettings.java
> +    static Builder builder() {
Copy pasta... agreed

2023-09-12 22:11 UTC, jyemin commented on driver-core/src/main/com/mongodb/connection/netty/NettyStreamFactoryFactory.java
Agreed

2023-09-12 23:33 UTC, jyemin commented on driver-core/src/main/com/mongodb/connection/NettyTransportSettings.java
> +        public NettyTransportSettings build() {
Done

2023-09-12 23:34 UTC, jyemin commented on driver-core/src/main/com/mongodb/annotations/Evolving.java
> - *     <td>Doing so allows customizing API behavior.</td>
Done

2023-09-12 23:34 UTC, jyemin commented on driver-core/src/main/com/mongodb/connection/NettyTransportSettings.java
> +    static Builder builder() {
Done

2023-09-12 23:38 UTC, jyemin commented on driver-core/src/main/com/mongodb/connection/AsynchronousSocketChannelStreamFactoryFactory.java
Done

2023-09-13 19:21 UTC, stIncMale commented
When I run `./gradlew clean check jar scalaCheck kotlinCheck testClasses docs -x test -x integrationTest -x spotlessApply` with `javac` 17.0.3, I am still getting lots of warnings. Here is an example:

> Task :driver-core:compileJava
/Users/valentin.kovalenko/Documents/projects/mongo-java-driver/driver-core/src/main/com/mongodb/MongoClientSettings.java:29: warning: [deprecation] StreamFactoryFactory in com.mongodb.connection has been deprecated
import com.mongodb.connection.StreamFactoryFactory;

2023-09-13 19:27 UTC, jyemin commented
>  I am still getting lots of warnings.

Yes, I mentioned that [here](https://github.com/mongodb/mongo-java-driver/pull/1195#pullrequestreview-1620955635), and gave several options for how to proceed.

2023-09-13 19:29 UTC, jyemin commented on driver-core/src/main/com/mongodb/connection/netty/NettyStreamFactoryFactory.java
Done

2023-09-13 19:29 UTC, jyemin commented on driver-core/src/main/com/mongodb/connection/TransportSettings.java
> +public abstract class TransportSettings {
Going once...

2023-09-13 19:59 UTC, jyemin commented on driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala
> +      "TransportSettings"
Done

2023-09-13 20:12 UTC, stIncMale commented
> Yes, I mentioned that https://github.com/mongodb/mongo-java-driver/pull/1195#pullrequestreview-1620955635, and gave several options for how to proceed.

Sorry, I thought the added `@SuppressWarnings("deprecation")` were supposed to solve that. I like _"2. Disable linting for deprecation_ combined with modified 3: live without the lint until it's time to remove the deprecated types for 5.0 (we'll move the program elements into the `internal` package, remove `@Deprecated` from them, enable the lint back again).

2023-09-13 20:13 UTC, stIncMale commented on driver-core/src/main/com/mongodb/connection/TransportSettings.java
> +public abstract class TransportSettings {
I am good with the name.

2023-09-13 20:27 UTC, jyemin commented
I went with option 2 and disabled linting for deprecation

2023-09-13 20:44 UTC, stIncMale commented
A fiew more suppressions are needed, as there are still some warnings (or, rather notes). Here is an example:

> Task :driver-sync:compileJava
Note: /Users/valentin.kovalenko/Documents/projects/mongo-java-driver/driver-sync/src/main/com/mongodb/client/internal/MongoClientImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

2023-09-13 20:52 UTC, stIncMale commented
No, I was wrong. `AbstractUnifiedTest` already specifies `@SuppressWarnings("deprecation")` at the class level, and the note is still there. I guess, it's supposed to be like that.

2023-09-13 20:52 UTC, stIncMale approved these changes

2023-09-13 20:56 UTC, jyemin commented
> I guess, it's supposed to be like that.

I'm mystified by the behavior of the compiler in this regard.

2023-09-14 13:34 UTC, rozza approved these changes
So whats next after this PR?

As internally we continue to use `StreamFactoryFactory` is there a ticket, I'm interested in what the alternative will look like.

2023-09-14 13:54 UTC, jyemin commented
> So whats next after this PR?

Similar to what we did with the Operation layer in 3.x.  We'll remove the two deprecated methods on MongoClientSettings, and then move all thee deprecated types to `com.mongodb.internal.connection`.  After that we can see if we want to refactor anything.  One obvious thing is to get rid of StreamFactoryFactory and just use StreamFactory directly.  Another is to get rid of `Stream#supportsAdditionalTimeout` as that was added only due to `Stream` being a public type. We'll also need to deal with the removal of `ServerAddress#getSocketAddress`, which we can do once `Stream` is no longer public.  There may be other simplifications, but these are the ones I'm aware of.

2023-09-14 13:59 UTC, merged