Deprecate options: maxTimeMS, maxCommitTimeMS for CRUD methods.
mongodb/mongo-java-driver pull request #1277
Opened 2023-12-09 02:33 UTC by vbabanin

JAVA-5264

2023-12-11 15:39 UTC, rozza requested changes
Looking good - Can you also add some `@SuppressWarnings("deprecation")` to the code, to quieten down the deprecation warnings when compiling.

2023-12-13 21:13 UTC, vbabanin commented
> Looking good - Can you also add some `@SuppressWarnings("deprecation")` to the code, to quieten down the deprecation warnings when compiling.

Done, thanks! I've added the `@SuppressWarnings("deprecation")`/@Suppress("DEPRECATION) annotations.

2023-12-14 10:54 UTC, rozza commented
`./gradlew clean check --continue -xtest -xintegrationTest` still reports lots of warnings

2024-01-03 15:59 UTC, rozza commented on driver-kotlin-sync/src/integration/kotlin/com/mongodb/kotlin/client/syncadapter/SyncAggregateIterable.kt
>      override fun maxTime(maxTime: Long, timeUnit: TimeUnit): SyncAggregateIterable<T> = apply {
nit: I would have just annoatated the whole method

2024-01-03 15:59 UTC, rozza approved these changes
LGTM

2024-01-04 03:55 UTC, merged