Convert legacy retryable writes tests to unified format
mongodb/mongo-java-driver pull request #1322
Opened 2024-03-01 14:29 UTC by jyemin

JAVA-5341

2024-03-01 15:44 UTC, jyemin commented on driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedRetryableWritesTest.java
> +        // Remove all this as part of JAVA-5125
These same tests are skipped in the legacy runner

2024-03-01 15:44 UTC, jyemin commented on driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedRetryableWritesTest.java
> +            assumeFalse(description.equals("RetryableWriteError label is added based on writeConcernError in pre-4.4 mongod response"));
This is actually not one of the converted tests.  Rather, it's a new unified test that was added independently and is in our backlog to add.  I'll update the description of that ticket to indicate the test has been merged but is being skipped.

Given that this is 4.2, it's unlikely we'll ever invest in fixing this.

2024-03-05 22:06 UTC, stIncMale requested changes

2024-03-05 23:33 UTC, jyemin commented on driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedRetryableWritesTest.java
> +        // Remove all this as part of JAVA-5125
Done

2024-03-05 23:37 UTC, stIncMale approved these changes

2024-03-05 23:48 UTC, merged