Optimize GridFS throughput by removing redundant byte array cloning.
mongodb/mongo-java-driver pull request #1402
Opened 2024-05-28 06:02 UTC by vbabanin

JAVA-5485

2024-06-03 19:58 UTC, jyemin requested changes
Code style suggestions.  Otherwise LGTM assuming performance is improved.

2024-06-03 19:58 UTC, jyemin commented on driver-sync/src/main/com/mongodb/client/gridfs/GridFSDownloadStreamImpl.java
> +        if (chunk == null || chunk.get("n").asInt32().getValue() != expectedChunkIndex) {
```suggestion
        if (chunk == null || chunk.getInt32("n").getValue() != expectedChunkIndex) {
```

2024-06-03 19:58 UTC, jyemin commented on driver-sync/src/main/com/mongodb/client/gridfs/GridFSDownloadStreamImpl.java
> +        byte[] data = chunk.get("data").asBinary().getData();
```suggestion
        byte[] data = chunk.getBinary("data").getData();
```

2024-06-04 08:51 UTC, rozza commented on driver-sync/src/main/com/mongodb/client/gridfs/GridFSDownloadStreamImpl.java
> +            if (chunk.get("n").asInt32().getValue() != startChunkIndex) {
```suggestion
            if (chunk.getInt32("n").getValue() != startChunkIndex) {
```

2024-06-04 14:32 UTC, jyemin approved these changes

2024-06-05 08:14 UTC, rozza approved these changes

2024-06-05 08:15 UTC, rozza commented
LGTM - great find and fix, quite a subtle change / fix.

2024-06-05 12:55 UTC, merged