Fix exception propagation in Async API methods
mongodb/mongo-java-driver pull request #1479
Opened 2024-08-14 03:16 UTC by vbabanin

- Resolve an issue where exceptions thrown during thenRun, thenSupply, and related operations in the asynchronous API were not properly propagated to the completion callback. This issue was addressed by replacing `unsafeFinish` with `finish`, ensuring that exceptions are caught and correctly passed to the completion callback when executed on different threads.

- Update existing Async API tests to ensure they simulate separate async thread execution.

JAVA-5562

2024-08-14 09:01 UTC, rozza requested changes
Looks really good.

However, one test in evergreen seems to be failing: `com.mongodb.reactivestreams.client.unified.LoadBalancerTest` which needs investigation before I can LGTM

2024-08-15 23:24 UTC, vbabanin commented on driver-core/src/main/com/mongodb/internal/async/AsyncFunction.java
> +                    throw new AssertionError("Callback has been already completed. It could happen "
Makes sense! I have included them in the message. Thanks!

2024-08-19 14:11 UTC, rozza approved these changes
LGTM!

2024-08-19 18:04 UTC, vbabanin commented
The Async API is currently utilized in the OIDC, Authenticator, and InternalStreamConnection components. I have conducted additional OIDC tests to verify the changes, and all results are green::

[OIDC Auth Test](https://spruce.mongodb.com/task/mongo_java_driver_oidc_auth_test_oidc_auth_test_patch_81402ae070244dfe5ba8f70d93b00798d8dd39c7_66bfeb9414f2af00076e9ceb_24_08_17_00_15_18/logs?execution=0)
[Azure OIDC Auth Test](https://spruce.mongodb.com/task/mongo_java_driver_testazureoidc_variant_oidc_auth_test_azure_patch_81402ae070244dfe5ba8f70d93b00798d8dd39c7_66bfeb9414f2af00076e9ceb_24_08_17_00_15_18/logs?execution=1)
[GCP OIDC Auth Test](https://spruce.mongodb.com/task/mongo_java_driver_testgcpoidc_variant_oidc_auth_test_gcp_patch_81402ae070244dfe5ba8f70d93b00798d8dd39c7_66bfeb9414f2af00076e9ceb_24_08_17_00_15_18/logs?execution=0)

2024-08-19 18:10 UTC, merged