Add regex operator to Atlas Search
mongodb/mongo-java-driver pull request #1587
Opened 2024-12-23 18:57 UTC by joykim1005

### Ticket
[JAVA-5726](https://jira.mongodb.org/browse/JAVA-5726)

### Description
There are several Atlas Search query operators that are not implemented with first class support in the Java driver. This PR adds the `regex` operator to Atlas Search.

### Testing
- [X] ran `./gradlew check`
- [X] ran `atlas-search-test` on Evergreen
- [X] ran `SearchOperatorTest`
- [X] ran all [Evergreen patch ](https://spruce.mongodb.com/version/6769aa5a191fe8000776f2d5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

2025-01-09 23:24 UTC, katcharov requested changes
Just a couple of minor nits.

2025-01-09 23:24 UTC, katcharov commented on driver-core/src/main/com/mongodb/client/model/search/SearchConstructibleBsonElement.java
> +    }
```suggestion
    public RegexSearchOperator allowAnalyzedField(final boolean allowAnalyzedField) {
        return newWithAppendedValue("allowAnalyzedField", allowAnalyzedField);
    }
```
Redundant null check. For naming, a similar method uses the same param name as the method itself:

```
    public SearchOptions returnStoredSource(final boolean returnStoredSource) {
        return newAppended("returnStoredSource", new BsonBoolean(returnStoredSource));
    }
```

This can be changed in the interfaces as well.

2025-01-09 23:24 UTC, katcharov commented on driver-core/src/main/com/mongodb/client/model/search/RegexSearchOperator.java
> +     * @param isAllowed The boolean to run the query against an analyzed field.
```suggestion
     * @param isAllowed Must be set to true if the query is run against an analyzed field.
```

2025-01-10 16:14 UTC, joykim1005 commented on driver-core/src/main/com/mongodb/client/model/search/SearchConstructibleBsonElement.java
> +    }
Got it.

2025-01-10 16:15 UTC, joykim1005 commented on driver-core/src/main/com/mongodb/client/model/search/RegexSearchOperator.java
> +     * @param isAllowed The boolean to run the query against an analyzed field.
Done

2025-01-13 17:49 UTC, katcharov approved these changes

2025-01-13 20:09 UTC, katcharov requested changes

2025-01-13 23:50 UTC, stIncMale commented on driver-core/src/main/com/mongodb/client/model/search/RegexSearchOperator.java
> +    RegexSearchOperator allowAnalyzedField(boolean allowAnalyzedField);
Could you please clarify what the suggestion is?

> set it to true as part of the plain regex builder

I am guessing, the "plain regex builder" means the `SearchOperator.regex` methods. Does that mean that the suggestion is to just always set `allowAnalyzedField` to `true` when `SearchOperator.regex` is called, thus "hiding" the existence of this field, and not allowing it to be `false`/absent?

> The operation will not change the original data

What operation does this refer to? The [`$search`](https://www.mongodb.com/docs/atlas/atlas-search/aggregation-stages/search/) aggregation pipeline indeed does not have the capacity to change the data being searched, but I am not sure why it is important here.

2025-01-14 19:50 UTC, joykim1005 commented on driver-core/src/main/com/mongodb/client/model/search/RegexSearchOperator.java
> +    RegexSearchOperator allowAnalyzedField(boolean allowAnalyzedField);
Synced offline and concluded that we should delete `allowAnalyzedField` from `regex` and `wildcard` operators as it could be deprecated in the future, meaning the users will have no "supported" way to set it. However, the users can set the field manually or use raw Bson.

2025-01-15 19:04 UTC, joykim1005 commented
`com.mongodb.client.ClientSideEncryptionE…estExternal_withExternalKeyVault__false` is failing and is unlikely caused by this PR and is happening in others as well.

2025-01-16 14:44 UTC, katcharov approved these changes
LGTM

2025-01-16 16:56 UTC, merged