Add queryString operator to Atlas Search
mongodb/mongo-java-driver pull request #1588
Opened 2024-12-26 04:03 UTC by joykim1005

Ticket
[JAVA-5727](https://jira.mongodb.org/browse/JAVA-5727)

Description
There are several Atlas Search query operators that are not implemented with first class support in the Java driver. This PR adds the queryString operator to Atlas Search.

Testing
- [X] ran ./gradlew check
- [X] ran atlas-search-test on Evergreen
- [X] ran SearchOperatorTest
- [X] ran [everygreen patch](https://spruce.mongodb.com/version/676cd53717f01a0007ccdddf/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) on all tests

2025-01-09 23:36 UTC, katcharov requested changes

2025-01-09 23:36 UTC, katcharov commented on driver-core/src/main/com/mongodb/client/model/search/SearchOperator.java
> +    static QueryStringSearchOperator queryString(final SearchPath defaultPath, final String query) {
I think it should not be possible to write `queryString(wildcardPath(...` - though the query supports wildcards, I believe the defaultPath itself does not. Could you confirm?

2025-01-10 16:32 UTC, joykim1005 commented on driver-core/src/main/com/mongodb/client/model/search/SearchOperator.java
> +    static QueryStringSearchOperator queryString(final SearchPath defaultPath, final String query) {
You are right, I mistook query supporting wildcards with the defaultPath being able to support it too. Will go ahead and change it!

2025-01-10 16:51 UTC, joykim1005 commented on driver-core/src/main/com/mongodb/client/model/search/SearchOperator.java
> +    static QueryStringSearchOperator queryString(final SearchPath defaultPath, final String query) {
You're right, will change `SearchPath` to `FieldSearchPath` to limit defaultPath to use wildcardPath!

2025-01-10 17:28 UTC, nhachicha commented on driver-scala/src/main/scala/org/mongodb/scala/model/search/SearchOperator.scala
> +  def queryString(defaultPath: SearchPath, query: String): QueryStringSearchOperator =
Shouldn't we also include the `score` parameter? (see example https://www.mongodb.com/docs/atlas/atlas-search/queryString/)

2025-01-10 17:41 UTC, joykim1005 commented on driver-scala/src/main/scala/org/mongodb/scala/model/search/SearchOperator.scala
> +  def queryString(defaultPath: SearchPath, query: String): QueryStringSearchOperator =
I left out the `score` as a parameter since it's an optional field and instead have it in the interface. All the other search operators also include `score` in the interface with overrides!

2025-01-13 21:15 UTC, katcharov approved these changes

2025-01-16 18:42 UTC, merged