Update compatibility for 3.12
mongodb/mongo-java-driver pull request #577
Opened 2020-09-22 15:48 UTC by rozza

JAVA-3822 JAVA-3837

http://rozza.github.io/mongo-java-driver/3.12/upgrading/

2020-09-22 15:49 UTC, rozza commented on docs/reference/content/upgrading.md
> -|Java Driver Version|MongoDB 2.6|MongoDB 3.0 |MongoDB 3.2|MongoDB 3.4|MongoDB 3.6|MongoDB 4.0|MongoDB 4.2|
Slightly controversially I had to remove MongoDB 2.6 to get all the columns to fit

2020-09-22 16:01 UTC, jyemin requested changes

2020-09-22 16:01 UTC, jyemin commented on docs/reference/content/upgrading.md
> +\* The 3.12 driver has been tested against MongoDB 4.4 but does not support all the new features
`\*` is the escape sequence?

2020-09-23 08:37 UTC, rozza commented on docs/reference/content/upgrading.md
> +\* The 3.12 driver has been tested against MongoDB 4.4 but does not support all the new features
Yes - stops it being a bullet point.

2020-09-23 08:39 UTC, rozza commented on docs/reference/content/upgrading.md
> +Please also note that 3.12.x has been tested against MongoDB 4.4, however support for all the new features is only available via a 4.x driver.
Updated

2020-09-23 14:57 UTC, jyemin approved these changes

2020-09-23 14:57 UTC, jyemin commented
LGTM

2020-09-24 08:53 UTC, merged