Add reference docs for explain of find and aggregate
mongodb/mongo-java-driver pull request #626
Opened 2021-01-07 17:30 UTC by jyemin

JAVA-3909

2021-01-08 14:30 UTC, rozza reviewed
Shouldn't examples be added to reactive & scala as well?

2021-01-10 14:58 UTC, jyemin commented
Added reactive and scala docs

2021-01-11 13:22 UTC, rozza requested changes

2021-01-11 14:05 UTC, jyemin commented on docs/reference/content/driver-reactive/tutorials/aggregation.md
> +[`AggregateIterable.explain()`]({{< apiref "mongodb-driver-reactivestreams" "com/mongodb/client/AggregateIterable.html#explain()" >}})
Copy pasta.  Done.

2021-01-11 14:05 UTC, jyemin commented on docs/reference/content/driver-reactive/tutorials/perform-read-operations.md
> +[`FindIterable.explain()`]({{< apiref "mongodb-driver-reactivestreams" "com/mongodb/client/FindIterable.html#explain()" >}})
Done

2021-01-11 14:05 UTC, jyemin commented on docs/reference/content/driver-scala/tutorials/aggregation.md
> +[`AggregateIterable.explain()`]({{< apiref "mongo-scala-driver" "com/mongodb/client/AggregateIterable.html#explain()" >}})
Done

2021-01-11 14:05 UTC, jyemin commented on docs/reference/content/driver-scala/tutorials/perform-read-operations.md
> +[`FindIterable.explain()`]({{< apiref "mongo-scala-driver" "com/mongodb/client/FindIterable.html#explain()" >}})
Done

2021-01-11 14:06 UTC, rozza approved these changes
LGTM!

2021-01-11 14:08 UTC, merged