Redaction improvements
mongodb/mongo-java-driver pull request #739
Opened 2021-06-29 19:48 UTC by jyemin

* Ensure command event for hello with speculativeAuthenticate is elided
* Ensure redacted commands are logged with elision

JAVA-4195

2021-06-30 16:05 UTC, stIncMale requested changes

2021-06-30 18:13 UTC, jyemin commented on driver-core/src/main/com/mongodb/internal/connection/LoggingCommandEventSender.java
> +            String commandString = redactionRequired ? String.format("{\"%s\": ...", commandName) : getTruncatedJsonCommand();
I had it that way initially, and then changed it to the way it is.  Here's why I think it's better this way:

* Redaction conditionals for succeeded and failed events are both handled in the top level method, so this makes it consistent between all three methods
* The purpose of getTruncatedJsonCommand is to truncate a potentially large JSON document.  Adding a conditional there for redaction muddies its purpose.  Redaction != truncation

Let me know if you still disagree.

2021-06-30 23:00 UTC, stIncMale commented on driver-core/src/main/com/mongodb/internal/connection/LoggingCommandEventSender.java
> +            String commandString = redactionRequired ? String.format("{\"%s\": ...", commandName) : getTruncatedJsonCommand();
Ok, thank you for explaining.

2021-06-30 23:00 UTC, stIncMale approved these changes

2021-07-01 13:04 UTC, rozza approved these changes
LGTM

2021-07-01 13:35 UTC, merged