JAVA-4421: Remove errorLabels from WriteConcernError
mongodb/mongo-java-driver pull request #840
Opened 2021-12-09 21:30 UTC by ramasai1

Currently I am unable to run tests. I am running `./gradlew test` and nothing happens. The timer keeps going but none of the tests are actually run. I put this up to get my approach verified.

2021-12-10 18:45 UTC, stIncMale commented
> Currently I am unable to run tests. I am running ./gradlew test and nothing happens.

Just in case, I am throwing everything that comes to mind regarding running the tests locally:

- JDK17.
- A accessible MongoDB listening on localhost:27017 and with enabled test commands at the very least. I create mine via [mtools](https://blog.rueckstiess.com/mtools/) with either of the three following commands:
  - `mlaunch init --single --port 27017 --storageEngine=wiredTiger --setParameter enableTestCommands=1 -v`
  - `mlaunch init --replicaset --nodes 3 --port 27017 --storageEngine=wiredTiger --setParameter enableTestCommands=1 -v`
  - `mlaunch init --sharded 2 --mongos 1 --config 1 --replicaset --nodes 3 --port 27017 --storageEngine=wiredTiger --setParameter enableTestCommands=1 -v`
- Compile and run tests:
   - `./gradlew check`

2021-12-14 14:56 UTC, ramasai1 commented
Thanks! I was running my DB on a different port and was under the impression that it was on 27017. 
Due to 2 constructors being annotated with `@Deprecated` in `MongoWriteConcernException`, there are a couple of deprecation warnings that are part of building the driver. These are in [`MongoOperationPublisher`](https://github.com/mongodb/mongo-java-driver/blob/master/driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java#L488) and [`MongoCollectionImpl`](https://github.com/mongodb/mongo-java-driver/blob/master/driver-sync/src/main/com/mongodb/client/internal/MongoCollectionImpl.java#L1014). Should these be marked with `@SuppressWarnings`? Or should I be passing in an empty error labels `BsonArray`? @jyemin @stIncMale

2021-12-21 19:05 UTC, jyemin requested changes
> Or should I be passing in an empty error labels BsonArray

Yes, might as well, since right after that the errorLabels are added

2021-12-21 19:05 UTC, jyemin commented on driver-core/src/main/com/mongodb/bulk/WriteConcernError.java
> +    @Deprecated private final Set<String> errorLabels;
Moved this to the getter and add an `@deprecated` Javadoc tag.

2021-12-21 19:05 UTC, jyemin commented on driver-core/src/main/com/mongodb/internal/operation/WriteConcernHelper.java
> +                writeConcernErrorDocument.getDocument("errInfo", new BsonDocument()));
What was the rationale for changing this?  The property is deprecated, but until it's removed it should continue to work as it does.

2022-01-05 16:11 UTC, ramasai1 reviewed
Added `@Deprecated` tags where necessary.

2022-01-05 16:13 UTC, ramasai1 commented on driver-core/src/main/com/mongodb/bulk/WriteConcernError.java
> +     * @deprecated Prefer using error labels included in the top level response document
Copied this from the ticket because I could not think of a better note.

2022-01-12 21:40 UTC, merged