Add CodecRegistries#withUuidRepresentation factory method
mongodb/mongo-java-driver pull request #864
Opened 2022-01-31 19:05 UTC by jyemin

JAVA-4461

Replaces internal API `CodecRegistryHelper#createRegistry`.

2022-01-31 19:08 UTC, jyemin commented on bson/src/main/org/bson/codecs/configuration/CodecRegistries.java
> +        if (codecRegistry instanceof OverridableUuidRepresentationCodecRegistry
Note that due to it being public the contract has changed a bit.  In the internal API, we could assume that the registry passed to `CodecRegistryHelper#createRegistry` was not itself an instance of  `OverridableUuidRepresentationCodecRegistry`.  But with the new method being public, we can't.  So the check becomes this instead.  So effectively, calling:

   withUuidRepresentation(withUuidRepresentation(registry, STANDARD), STANDARD)

is a no-op.

2022-02-01 09:27 UTC, rozza approved these changes

2022-02-01 09:30 UTC, rozza commented on bson/src/main/org/bson/codecs/DocumentCodec.java
> +        if (this.uuidRepresentation.equals(uuidRepresentation)) {
Ack

2022-02-03 18:01 UTC, stIncMale requested changes

2022-02-03 21:34 UTC, jyemin commented on bson/src/main/org/bson/codecs/configuration/CodecRegistries.java
> +            return new OverridableUuidRepresentationCodecRegistry(codecRegistry, uuidRepresentation);
I like it!  Done.

2022-02-03 23:01 UTC, stIncMale approved these changes

2022-02-03 23:03 UTC, merged