Support clustered index on a collection
mongodb/mongo-java-driver pull request #934
Opened 2022-05-09 23:24 UTC by jyemin

JAVA-4576

2022-05-12 22:23 UTC, stIncMale requested changes

2022-05-12 22:23 UTC, stIncMale commented on driver-core/src/main/com/mongodb/client/model/ClusteredIndexOptions.java
> +    }
Would it be better to return `this` here?

2022-05-12 22:23 UTC, stIncMale commented on driver-core/src/main/com/mongodb/internal/operation/CreateCollectionOperation.java
> +    public CreateCollectionOperation clusteredIndexName(final String clusteredIndexName) {
Let's mark `clusteredIndexName` as `@Nullable`, because we indeed may pass `null` when calling this method in `MongoOperationPublisher`.

2022-05-12 22:23 UTC, stIncMale commented on driver-core/src/main/com/mongodb/client/model/ClusteredIndexOptions.java
> +        this.key = key;
I propose `this.key = notNull("key", key)`.

2022-05-13 21:43 UTC, stIncMale approved these changes

2022-05-16 08:23 UTC, rozza approved these changes

2022-05-16 12:47 UTC, merged