Update project dependencies to latest available
mongodb/mongo-java-driver pull request #990
Opened 2022-08-22 13:51 UTC by jyemin

JAVA-4710

Note: Updating Jupiter dependency caused a strange Gradle build failure, so leaving that one alone for now.

2022-08-22 14:32 UTC, rozza commented on build.gradle
> +    projectReactorVersion = '2020.0.22'
Is this a big update / breaking change. I recall last time we were hesitant to use the latest version.

2022-08-22 14:51 UTC, rozza commented on build.gradle
> +    projectReactorVersion = '2020.0.22'
Ack

2022-08-22 14:57 UTC, rozza requested changes
Can you rebase? A `@NotNull` snuck in for a `@NonNull` in master breaking the tests.

2022-08-22 15:03 UTC, jyemin commented
Yes, done.  Sorry about that, I don't know how I missed it.

2022-08-23 08:04 UTC, rozza approved these changes
LGTM!

2022-08-23 11:25 UTC, merged